In [ ]:
import numpy as np
array = np.array([2,4,6,8])


[2 4 6 8]


In [ ]:
print("Type Check: ", type(array))
print("Dimension: ", array.ndim)



Type Check:  <class 'numpy.ndarray'>
Dimension:  1


In [ ]:
import numpy as np3

#2D array
B = np3.array([ [1,2,3,4,5] , [6,7,8,9,10] ])
print(B)
print("Dimension: ", B.ndim)

#3D array
C = np3.array( [ [ [1,2,3,4,5] , [6,7,8,9,10], [11,12,13,14,15] ] ])
print(C)
print("Dimension: ", C.ndim)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Dimension:  2
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
Dimension:  3


In [ ]:
#Slicing in Python
arr = np.array([1,2,3,4,5])
print("Slicing 1 to 2: ", arr[1:3])
print("Slicing O to 2: ", arr[:3])



Slicing:  [1 2 3]


In [ ]:
#Looping through an array

even = np.array( [ [ [2,4,6,8,10],[12,14,16,18,20],[22,24,26,28,30] ] ] )

for i in even:
  for x in i:
    for y in x:
      print(y)


2
4
6
8
10
12
14
16
18
20
22
24
26
28
30


In [ ]:
#Concatenating Array

arr1 = np.array([1,2])
arr2 = np.array([3,4])

arr3 = np.concatenate((arr1, arr2))
print(arr3)

[1 2 3 4]


In [ ]:
print("Hello!")

Hello!


In [ ]:
# Lab Task 3

import numpy as np

matrix = np.arange(2, 11).reshape(3, 3)
print("3x3 matrix:")
print(matrix)

float_matrix = matrix.astype(float)
print(float_matrix)
print("Data type of the matrix:", float_matrix.dtype)

# maximum and minimum value of the flattened array
max_value = float_matrix.max()
min_value = float_matrix.min()

print("\nMaximum value :", max_value)
print("Minimum value :", min_value)

Original 3x3 matrix:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

Matrix converted to float type:
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
Data type of the matrix: float64

Maximum value of the flattened array: 10.0
Minimum value of the flattened array: 2.0
